### ISSUE TITLE
reading the board state inside the event loop

### ISSUE THREAD

**Issue by cemox** [niklasf/python-asyncdgt#1]
Hi, I am developing a simple application for raspberry-pi. Everything works fine, but at times I need to read the board position in order to compare the actual position of the pieces of the board to the board position which is tracked in the memory. It is a sort of consistency check between the physical position of the pieces on the board and the position of the pieces in the memory. (Suppose that you accidentally hit the pieces). When I try to do this, I receive the error "even loop is running". 

Is there a way of reading the board state without waiting for a event emitter to take place?

**Comment by cemox** [comment]
Sorry, I solved the problem by emitting the event. (dgt.emit("board"))

**Comment by cemox** [comment]
My dgt board works fine with @dgt.on("board"), whenever the pieces on the board change, it triggers.
But I also want to check the board state when there is no change on the board. I still cannot succeed to get the board whenever I wanted.

**Comment by niklasf** [comment]
Hi. Does

```python
board = await dgt.get_board()
```

not work?

**Comment by cemox** [comment]
No it does not work :(

**Comment by niklasf** [comment]
Is there an error?
