### ISSUE TITLE
problems on Windows

### ISSUE THREAD

**Issue by ghost** [niklasf/python-asyncdgt#2]
Hi. I find out it doesn't work on Windows. Is it true?
Is there an easy way to use it on Windows?

**Comment by niklasf** [comment]
Hi. Currently I don't have Windows to test. What did you try? What did you expect to happen and what exactly happened instead?

**Comment by ghost** [comment]
termios:
This module provides an interface to the POSIX calls for tty I/O control. It is only available for those Unix versions that support POSIX termios style tty I/O control configured during installation.

fcntl: 
It is an interface to the fcntl() and ioctl() Unix routines.

**Comment by niklasf** [comment]
The locking is helpful to avoid multiple applications doing conflicting operations on the serial port, but otherwise optional. So should be easy to fix. I'll try it next time I have my hands on a Windows machine.
