### ISSUE TITLE
little bug in documentation ? 

### ISSUE THREAD

**Issue by ccanger** [niklasf/python-asyncdgt#3]
Hi Niklas, 

Thank you for your good work. Can it be that in the documentation a bug is:

Quote:
dgt = asyncdgt.auto_connect (["/ dev / ttyACM *"], loop)
and right would be:
dgt = asyncdgt.auto_connect ([loop, ["/ dev / ttyACM *"])

It may be that it affects all the lines of documentation.

**Comment by niklasf** [comment]
Indeed, thanks. Updated the snippet for now.

The argument order is a bit unconventional. In a future version loop should probably be last, or even optional.
